POST http://localhost:8081/post 
Content-Type: application/json
Accept: application/json

{
    "date": "22 Jan 2021",
    "description": "Hello Everyone",
    "id": "ynbfvhgbkh",
    "likes": 15,
    "location": "Bangalore",
    "name": "Suryakumar Yadav"
}